### ISSUE TITLE
Swerve improvments

### ISSUE THREAD

**Issue by allengregoryiv** [Spectrum3847/2024-SpectrumSim#12]
Add some of the features and control modes from the 2024 Ultraviolet repo.

Things like 
- Heading Lock Drive
- Snap turns on the left stick (stickSteerDrive() )
- reorient on the dpad
- xbrake (turn all the wheels to face in, like an x from above)
- fpvMode()

**Comment by cycIes** [comment]
The above features have been added. Please let me know if there are any mistakes or other things that should be implemented.

**Comment by allengregoryiv** [comment]
@cycIes I looked at things, I made some update, moved the Swerve methods to return Commands and then just have the Swerve Command methods call those, it's a little cleaner and we have less things exposed from Swerve directly.

I also made the Swerve methods protected. In general Mechanism methods should be Protected or blank, and the MechanismCommand methods should be public.

Similarly I think we should move the triggers to the MechanismCommands Class too but we may need to rename it to something else.

Xbrake I don't think does what it's supposed to be the Setpoints object is never used inside of Swerve.

**Comment by allengregoryiv** [comment]
I'm gonna pull request this to main and then we can fix xbrake after we move to 2025. I'm not sure how much of swerve we are gonna have to change.

**Comment by cycIes** [comment]
When I tested xbrake in sim, I thought it seemed to work but maybe the robot only stops because the command requires the subsystem? Setpoints doesn't appear to be used in Ultraviolet outside of logging.

**Comment by SpectrumFRC3847** [comment]
Interesting thanks for looking into that, you are probably right
